# Generated by Django 4.1.1 on 2024-11-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_publish', 'Can publish questions')]},
        ),
    ]
