# Generated by Django 4.1.1 on 2024-11-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_options'),
        ('polls', '0002_vote'),
    ]

    operations = [
    ]
